### ISSUE TITLE
Multiline selection is a bit broken

### ISSUE THREAD

**Issue by Guldoman** [adamharrison/lite-xl-terminal#10]
[Video del 2023-08-11 00-34-30.webm](https://github.com/adamharrison/lite-xl-terminal/assets/2798487/05aa3ae9-4983-456b-8860-9ca446a37fba)

**Comment by adamharrison** [comment]
Huh. Odd. OK. Will look into.

**Comment by adamharrison** [comment]
Should be fixed by 5350015a6515480a5be3938595dab8c54ea0e16d.

**Comment by Guldoman** [comment]
Yep, fixed.
