### ISSUE TITLE
Segmentation fault under Windows

### ISSUE THREAD

**Issue by Kabcorp** [adamharrison/lite-xl-terminal#12]
1/3 times I use Terminal:Toggle, I have a segfault on Windows 10.
DLL from 2023-08-20 01:39
![image](https://github.com/adamharrison/lite-xl-terminal/assets/33150965/fb3815fa-e4d3-4918-88c6-6c82fe206e4e)

**Comment by Guldoman** [comment]
In `gdb`, could you run the `bt` command?

**Comment by Kabcorp** [comment]
![image](https://github.com/adamharrison/lite-xl-terminal/assets/33150965/6d851da5-ada8-42d0-9bc9-e4ff665fbd8a)

**Comment by adamharrison** [comment]
Hrm. Interesting. OK. Don't have access to my windows machine atm so harder for me to debug, but can probably find out what's up by end of week or so; after which I'll probably make a 1.0 release.

**Comment by adamharrison** [comment]
I'm not actually able to replicate this on my side, but 2a82414c24f0d6633cfe8551abaf59be3b7be8d8 may fix this, as there was some wonky sizing on Windows for some reason.

Can you try and reproduce with that, and let me know?

**Comment by Kabcorp** [comment]
Yes, I have the same issue, so same backtrace in gdb.
It you toggle the terminal many times, it's not crashing for you?
If not, I bet it's as usual a windows issue from the C code.

**Comment by adamharrison** [comment]
Yeah; it's not happening for me when I toggle the terminal; I did it like 20-30 times, and didn't hit anything. So it's probably undefined behaviour somewhere.

Hrm. Can you compile with debug info? (`./build.sh -g`), and then try and get the backtrace? It should give the line numbers at that point, which'll help me narrow this down.

**Comment by adamharrison** [comment]
Some further debugging: The reason I couldn't reproduce is because I was running through msys, which sets $SHELL to bash.  So this only happens with `cmd.exe`. Sometimes, it simply can't create that process. Will try to investigate why, but may be irreconcilable depending on why windows isn't letting us create the process.

**Comment by adamharrison** [comment]
@Kabcorp OK! Think c785a8acbc9af96be11867a133dec563798e2ac3 fixed it.

**Comment by Kabcorp** [comment]
No crash at all. Thank you sir!
