### ISSUE TITLE
Undefined globals

### ISSUE THREAD

**Issue by jgmdev** [adamharrison/lite-xl-terminal#14]
![undefined-global-1](https://github.com/adamharrison/lite-xl-terminal/assets/1702572/973d8227-b70c-46c3-b1c5-8d2a9b86e6e5)
![undefined-global-2](https://github.com/adamharrison/lite-xl-terminal/assets/1702572/784ce28f-7ce3-47fa-9717-c81339d2a525)
![undefined-global-3](https://github.com/adamharrison/lite-xl-terminal/assets/1702572/9db13292-621f-440c-a845-7fc748ef9c26)

**Comment by adamharrison** [comment]
Also fixed, thank you.
