### ISSUE TITLE
Colors are a bit broken

### ISSUE THREAD

**Issue by Guldoman** [adamharrison/lite-xl-terminal#16]
Since 32ec0da2d43d236805f77e091fb3003def2e4ec9 some text is invisible/has the same color as the background.

[Video del 2023-08-22 06-04-30.webm](https://github.com/adamharrison/lite-xl-terminal/assets/2798487/7d095931-2c2d-44ee-ae33-b738ca356f14)

Before:
![Schermata del 2023-08-22 06-06-35](https://github.com/adamharrison/lite-xl-terminal/assets/2798487/fa857398-56f8-42b1-95c3-86f0682dc4f6)

**Comment by adamharrison** [comment]
So if you disable `bold_text_in_bright_colors` this is not a problem, yes?

**Comment by adamharrison** [comment]
Can you dump me for your `terminal.log`?

**Comment by adamharrison** [comment]
Perfect, thank you. Yeah the output looks fine, so something's wrong with our interpretation. Looking into.

**Comment by adamharrison** [comment]
Aha. Think I got it. Try master.

**Comment by Guldoman** [comment]
Yep fixed, thanks.
