### ISSUE TITLE
Some Characters not appearing (or are in black)

### ISSUE THREAD

**Issue by pegvin** [adamharrison/lite-xl-terminal#19]
## Info

- OS Info: `Linux debPC 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux`
- Terminal Emulator: `st (suckless terminal)`
- Shell: `zsh 5.9 (x86_64-debian-linux-gnu)`

## Issue

when writing an argument to a command or using the tab-autocomplete feature for file selection in zsh, many entries and characters don't appear at all, like it feels like they are in black or something but highlighting them does nothing too.

i am not using OhMyZsh or something, everything is solely configured by me, you can find my configuration here: https://github.com/pegvin/noodle/tree/master/noodle/.config/zsh

i have attached an example of the bug:

https://github.com/adamharrison/lite-xl-terminal/assets/75035219/48268de8-6b5f-4b33-8cfb-7d54ccea9d73

**Comment by adamharrison** [comment]
Can you confirm this still happens with Master? Feels like a duplicate of https://github.com/adamharrison/lite-xl-terminal/issues/16.

**Comment by pegvin** [comment]
my bad, i was on the commit in which you fixed the Line feed not being sent.

i just re-built and installed everything from master and it works like charm!

i'll just "watch" this repo to get update of any commits and stuff.

thanks magicians for doing your magic.
