### ISSUE TITLE
Caret should invert colors

### ISSUE THREAD

**Issue by Guldoman** [adamharrison/lite-xl-terminal#21]
Currently the caret hides the char behind, while it should behave like selections.
A "selected" caret should be "inverted twice" and go back to the original colors.

**Comment by adamharrison** [comment]
Yeahhhhh; I've been lazy about this. I know it should. I just haven't gotten around to it yet. Will do. Sometime.

**Comment by adamharrison** [comment]
OK, should be closed by [667f5be](https://github.com/adamharrison/lite-xl-terminal/commit/667f5becfb24f0cce504d9d7e86d4fa3e68c3548).

**Comment by Guldoman** [comment]
Awesome, thanks!
