### ISSUE TITLE
Closing window or drawer when using powershell crashes lite-xl

### ISSUE THREAD

**Issue by Alphinux** [adamharrison/lite-xl-terminal#25]
When I try to quit the terminal or close the drawer after accessing powershell by typing "powershell" in cmd.exe, the whole window becomes unresponsive.

**Comment by adamharrison** [comment]
Interesting. Will look at this and see what's going on. Probably address it later this week.

**Comment by adamharrison** [comment]
OK, yeah, confirmed this happens to me too. Attempting to fix.

**Comment by adamharrison** [comment]
OK! [cbcf2f1](https://github.com/adamharrison/lite-xl-terminal/commit/cbcf2f17a4ee4f8915ffdf7bf2ab5d8e4133ffc0) should fix this. Can you test it, and let me know? (You can pull the .dll directly form the "continous" release if you're having trouble building it).

**Comment by adamharrison** [comment]
I'm going to close this; please feel free to reopen if the bug still persists.
