### ISSUE TITLE
terminal windows don't support chinese!

### ISSUE THREAD

**Issue by zhouxs1023** [adamharrison/lite-xl-terminal#26]
terminal windows don't support chinese! 
chinese can not show correctly as below!
![123](https://github.com/adamharrison/lite-xl-terminal/assets/905931/2d9c5620-1987-4f73-a114-16008f633743)

**Comment by adamharrison** [comment]
This actually has to do with your font; you simply need to select a CJK font with config.plugins.terminal.font.

**Comment by zhouxs1023** [comment]
Can you provide more detailed explanation? I don't know which file to add ？
in lite-xl editor , add config.plugins.terminal.font into init.lua ,but don't effect
![123](https://github.com/adamharrison/lite-xl-terminal/assets/905931/d575003c-6761-4308-9b02-808a13a91c7e)
terminal show as below:
![234](https://github.com/adamharrison/lite-xl-terminal/assets/905931/5786b576-8834-4992-95dc-1f81fd091116)

**Comment by adamharrison** [comment]
Sorry about the dleay here.

That config line looks right.

You're sure `msyh.ttf` is in lite-xl's DATADIR? Are there any errors in your log? (You can run `Core: Open Log` to see it). It doesn't look like the font swtiched, so usually that's indicative of a loading error.

**Comment by zhouxs1023** [comment]
msyh.ttf is in lite-xl's DATADIR,and log as below
![123](https://github.com/adamharrison/lite-xl-terminal/assets/905931/447e7c7b-068f-4588-9 4b4-fd64b7f3ed9b)
![234](https://github.com/adamharrison/lite-xl-terminal/assets/905931/10a8c004-7430-425b-9ddc-50f458b087f7)
![345](https://github.com/adamharrison/lite-xl-terminal/assets/905931/a1bcef4c-088a-406c-8635-461d758bba39)
terminal windows still don't support chinese!

**Comment by zhouxs1023** [comment]
Use arial.ttf fonts for terminal ,still not show correctly,

**Comment by Guldoman** [comment]
AFAIK Arial doesn't have any CJK characters.

Check if `msyh` is named `msyh.ttf` or `msyh.ttc` and correct the line in your user module if it's the latter.

**Comment by zhouxs1023** [comment]
Use msyh.ttc is ok, problem had solved,Thank you very much
