### ISSUE TITLE
scroll through the document while the terminal is opened (auto-focus).

### ISSUE THREAD

**Issue by kemzops** [adamharrison/lite-xl-terminal#36]
https://github.com/adamharrison/lite-xl-terminal/assets/52936496/77c33c86-8c4c-48df-8857-cc38df9e5be8

https://github.com/adamharrison/lite-xl-terminal/assets/52936496/e5da16dd-b778-4e1d-ae1c-1e40857ba54c

**Comment by Guldoman** [comment]
Found the issue, PR incoming.

**Comment by adamharrison** [comment]
Damn guldo you scary

**Comment by Guldoman** [comment]
It was bugging me too, and it turned out to be simpler than expected.

**Comment by kemzops** [comment]
thanks @Guldoman !! it was very annoying :face_exhaling:
