### ISSUE TITLE
on Windows lpm install error

### ISSUE THREAD

**Issue by hoony0203** [adamharrison/lite-xl-terminal#40]
1. 
![제목 없음](https://github.com/adamharrison/lite-xl-terminal/assets/52574960/d8cc2315-37a4-4e6f-baf6-c61f47932abe)
lpm install terminal

checksum doesn't match for https://github.com/adamharrison/lite-xl-terminal/releases/download/v1.03/libterminal.x86_64-windows.dll; use --force to override

2. 
![제목 없음2](https://github.com/adamharrison/lite-xl-terminal/assets/52574960/44b17c9c-6803-40f9-8a4a-27f7c2bb2425)

lpm install terminal --force

warning: checksum doesn't match for https://github.com/adamharrison/lite-xl-terminal/releases/download/v1.03/libterminal.x86_64-windows.dll
can't find C:\Users\Administrator\.config\lite-xl\lpm\files\237ae1ecbda9c2ce5d4f29f015382ca4b6ddad798db340897695987bcd284d7e.part

**Comment by Guldoman** [comment]
With #41 this should be fixed.
You can test it with:
```
lpm install https://github.com/Guldoman/lite-xl-terminal:PR_update_x86_64-windows_checksum terminal
```

**Comment by hoony0203** [comment]
Thank you for fix this issue and lpm command.

**Comment by hoony0203** [comment]
Thank you for fix this issue and lpm command.
