### ISSUE TITLE
Terminal not accepting input until the first `update`

### ISSUE THREAD

**Issue by Guldoman** [adamharrison/lite-xl-terminal#42]
With something like:
```lua
local keymap = require "core.keymap"
local command = require "core.command"

keymap.add({
  ["f5"] = function()
    command.perform("terminal:execute", "echo command to run")
  end
})
```
the terminal doesn't receive any input the first time it's called.

I suspect it's because the terminal isn't spawned until the first `update` call, so `TerminalView:input` just returns.

**Comment by adamharrison** [comment]
f299a06

**Comment by Guldoman** [comment]
Perfect!
