### ISSUE TITLE
Toggle Focus between drawer and current tab

### ISSUE THREAD

**Issue by mizu-048** [adamharrison/lite-xl-terminal#53]
use some shortcut like `alt+shift+t` or `` alt+` ``
to toggle the focus between the terminal drawer and the current tab,

or is there an existing way? i couldn't find it

**Comment by adamharrison** [comment]
Hrm. Good point. I'll add this in.

**Comment by adamharrison** [comment]
OK! I liked this idea so much, that as of 79b8038, I changed `alt+t` to by default spawn a drawer if none exists, and if it does, swap to the drawer. If you have focus on the drawer, it swaps back to your previously active view.

I moved the original command for toggling a drawer to `shift+alt+t`.

Let me know if that works for you! As soon as Takase fixes the build box, I'll make a new release.

**Comment by mizu-048** [comment]
alright, thanks!
i was just used to this feature in vs code so requested, i don't have time these days so can't test (windows) will report if its broken

**Comment by adamharrison** [comment]
Sounds good, no worries.

**Comment by dlevear** [comment]
I tried it on my mac (just copying in the modified `init.lua`). So far it is working very well! I changed the keystroke to something else, because `alt+` keystrokes do not seem to work on the mac. This was exactly the feature I was missing, thank you for writing this.

**Comment by adamharrison** [comment]
No problem, glad I could help!
